#Test for all the Serialize/Parse functions.

#Merit Serialize.
import SerializeTests/SerializeMinersTest
import SerializeTests/SerializeBlockTest

#Lattice Serialize.
import SerializeTests/SerializeMintTest
import SerializeTests/SerializeClaimTest
import SerializeTests/SerializeSendTest
import SerializeTests/SerializeReceiveTest
import SerializeTests/SerializeDataTest
import SerializeTests/SerializeVerificationTest
import SerializeTests/SerializeMeritRemovalTest
