#Consensus Tests.

import ConsensusTests/ElementTest
import ConsensusTests/SendDifficultyTest
import ConsensusTests/DataDifficultyTest
import ConsensusTests/GasPriceTest
import ConsensusTests/MeritRemovalTest
import ConsensusTests/MeritHolderTest
import ConsensusTests/ConsensusTest
