#Modules Tests.

import ModulesTests/SystemModuleTest
import ModulesTests/TransactionsModuleTest
import ModulesTests/ConsensusModuleTest
import ModulesTests/MeritModuleTest
import ModulesTests/PersonalModuleTest
import ModulesTests/NetworkModuleTest
