#Merit Serialization Tests.

import Merit/SerializeDifficultyTest
import Merit/SerializeRecordsTest
import Merit/SerializeMinersTest
import Merit/SerializeBlockHeaderTest
import Merit/SerializeBlockBodyTest
import Merit/SerializeBlockTest
